### ISSUE TITLE
Log: use `tflog` instead of `stdout`

### ISSUE THREAD

**Issue by Nebulazhang** [hashicorp/terraform-provider-helm#1182]
### Description

Do we have any plan to upgrade helm-provider's log lib? 

According to this doc https://developer.hashicorp.com/terraform/plugin/log/managing#testing
Only the log set by `tflog` can be catch by Terraform 
(If I understand this doc correctly, please point out any errors if there are any)
 
Or how can I debug the helm-provider on the Terraform cloud?  How to see the `helm-provider` when I run it on the cloud?

Thansk

### References

https://developer.hashicorp.com/terraform/plugin/log/managing#testing

**Comment by arybolovlev** [comment]
Hi @Nebulazhang,

In order to debug Terraform, you can create an env variable `TF_LOG` with a desired value in your TFC workspace as it is explained here: https://support.hashicorp.com/hc/en-us/articles/360001113727-Enabling-trace-level-logs-in-Terraform-CLI-Cloud-or-Enterprise.

I will go ahead and close this issue as it doesn't seem to be related to the provider, but more about how to debug in the TFC.

Thank you.

**Comment by rattboi** [comment]
I believe you should reopen this. It's true that TF_LOG will give all logs, but if I want just the helm provider's logs, that's not possible today. Reading the link given in the original post, you'll see the following:

## TF_LOG_PROVIDER_{PROVIDER_NAME} (e.g., TF_LOG_PROVIDER_HELM)

> Only applies to providers that write logs using the tflog package. Does not affect logs written by legacy log.Print* functions.

I'd like to be able to set `TF_LOG_PROVIDER_HELM=DEBUG` and see only debug logs for the helm provider, not terraform overall.
