### ISSUE TITLE
Is #702 storing Helm Diff stable?

### ISSUE THREAD

**Issue by askerrit** [hashicorp/terraform-provider-helm#1216]
Hey!

Is this:
https://github.com/hashicorp/terraform-provider-helm/pull/702 
Stable and in the main branch yet? Or is it still considered experimental? I couldn't find any more info on it. I'd like to use it.

**Comment by sheneska** [comment]
Hi @askerrit, this has been merged and is proven to be stable, however we would need to make an internal decision to determine when this will be updated in our [documentation](https://registry.terraform.io/providers/hashicorp/helm/latest/docs#experiments). In the interim, you would need to look at the `experiments` attribute and set the appropriate flag to `true` in order to use it.
