### ISSUE TITLE
 403 Forbidden on public repository.

### ISSUE THREAD

**Issue by stobias123** [hashicorp/terraform-provider-helm#1291]
### Terraform, Provider, Kubernetes and Helm Versions
just trying to run on a public repo, get 403
```
│ Error: could not download chart: unexpected status from HEAD request to https://registry.dagger.io/v2/dagger-helm/dagger/manifests/0.0.2: 403 Forbidden
```
```
Terraform version:v1.4.6
Provider version:latest
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
just download the chart - I've confirmed I can with regular helm

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
@stobias123 Hello thank you for opening this issue, could you provide us with the exact repo that you're using? It seems like the only way to pull the chart that you've mentioned is from an OCI repo that i found from the dagger repository linked [here](https://github.com/dagger/dagger/blob/a499195df3de436969c4477bb1e9f074aa586eb6/docs/current/guides/194031-kubernetes.md?plain=1#L24C1-L31C4)

It could be that you're using a different repo rather than the OCI repo mentioned in the docs. Let me know if using that works for you!

**Comment by iBrandyJackson** [comment]
Without further feedback to proceed, we're closing this ticket to maintain clarity in our issue tracker. This closure is purely procedural; we're still interested in addressing your concerns.

Should this issue persist or if you have additional information to share, please feel free to open a new ticket. Your contributions are valuable to us, and we're keen to assist wherever possible.

**Comment by arthur-leclerc** [comment]
In case anyone lands here, [the Dagger documentation](https://docs.dagger.io/integrations/104820/kubernetes/#deployment-with-helm) explains how to install Chart like this:

```bash
helm upgrade --install --namespace=dagger --create-namespace \
    dagger oci://registry.dagger.io/dagger-helm
```

Which translates like this with the Helm provider:

```hcl
resource "helm_release" "this" {
  name       = "dagger"
  chart      = "dagger-helm"
  version    = "0.1.1"
  repository = "oci://registry.dagger.io"
}
```

The problem was probably that the repository used was `oci://registry.dagger.io/dagger-helm` instead of `oci://registry.dagger.io`.
