### ISSUE TITLE
Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-helm#138]
Hello.

We have faced with an issue:

```
Error: Error applying plan:

2 error(s) occurred:


* helm_release.ibm-worker-recovery: 1 error(s) occurred:

* helm_release.ibm-worker-recovery: rpc error: code = Unavailable desc = transport is closing
* helm_release.ibmcloud-block-storage-plugin: 1 error(s) occurred:

* helm_release.ibmcloud-block-storage-plugin: rpc error: code = Unavailable desc = transport is closing

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

helm module section is: 

```
resource "helm_repository" "ibm-chartmuseum" {
   depends_on = ["null_resource.config_edge_nodes"]
    name = "ibm-chartmuseum"
    url  = "https://registry.bluemix.net/helm/ibm/"
}

resource "helm_release" "ibmcloud-block-storage-plugin" {
depends_on = ["helm_repository.ibm-chartmuseum"]
name = "ibmcloud-block-storage-plugin"
namespace = "kube-system"
chart= "ibm-chartmuseum/ibmcloud-block-storage-plugin"
}


resource "helm_release" "ibm-worker-recovery" {
depends_on = ["helm_repository.ibm-chartmuseum"]
name = "ibm-worker-recovery"
namespace = "kube-system"
chart= "ibm-chartmuseum/ibm-worker-recovery"
} 
```

It's installs these charts thought, but return an issue.

Just for note - when I using local exec helm as bash, it working without issue, so it's not firewall or elsewhere.

Could you please help?

Terraform v0.11.8
+ provider.external v1.0.0
+ provider.helm (unversioned)
+ provider.ibm v0.11.3
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.random v2.0.0

I have tested with helm provider that installs with terraform init 0.1.0 and with installed manually 0.6.0

**Comment by denis111** [comment]
The same error here although I'm not sure it really installs charts but returns error.
`
provider "helm" {
  enable_tls = true
  insecure = false
}
`
when I execute 'helm ls --tls-verify' from bash it works fine.

**Comment by rporres** [comment]
@olegg8 That looks like provider has crashed and grpc connection between terraform and provider closes unexpectedly, hence terraform complains.

That can be due to a number of reasons. I'm afraid that without more detailed logs it's impossible to know what's going on. It may be a different case than the one @denis111 is suffering

**Comment by denis111** [comment]
@rporres Here are some logs:
```log
2018-10-30T15:58:44.539+0100 [DEBUG] plugin.terraform-provider-helm_v0.6.2_x4: 2018/10/30 15:58:44 [DEBUG] Created tunnel using local port: '33771'
2018-10-30T15:58:45.175+0100 [DEBUG] plugin.terraform-provider-helm_v0.6.2_x4: 2018/10/30 15:58:45 [DEBUG] could not get release rpc error: code = Unavailable desc = transport is closing
2018/10/30 15:58:45 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* helm_release.prometheus: rpc error: code = Unavailable desc = transport is closing
2018/10/30 15:58:45 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* helm_release.prometheus: rpc error: code = Unavailable desc = transport is closing
2018-10-30T15:58:45.229+0100 [DEBUG] plugin.terraform-provider-helm_v0.6.2_x4: 2018/10/30 15:58:45 [DEBUG] could not get release rpc error: code = Unavailable desc = transport is closing
2018/10/30 15:58:45 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* helm_release.grafana: rpc error: code = Unavailable desc = transport is closing
2018/10/30 15:58:45 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* helm_release.grafana: rpc error: code = Unavailable desc = transport is closing
2018-10-30T15:58:45.274+0100 [DEBUG] plugin.terraform-provider-helm_v0.6.2_x4: 2018/10/30 15:58:45 [DEBUG] could not get release rpc error: code = Unavailable desc = transport is closing
2018/10/30 15:58:45 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* helm_release.cert_manager: rpc error: code = Unavailable desc = transport is closing
2018/10/30 15:58:45 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* helm_release.cert_manager: rpc error: code = Unavailable desc = transport is closing
2018/10/30 15:58:45 [TRACE] [walkApply] Exiting eval tree: helm_release.cert_manager
2018-10-30T15:58:45.327+0100 [DEBUG] plugin.terraform-provider-helm_v0.6.2_x4: 2018/10/30 15:58:45 [DEBUG] could not get release rpc error: code = Unavailable desc = transport is closing
2018/10/30 15:58:45 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* helm_release.ingress: rpc error: code = Unavailable desc = transport is closing
2018/10/30 15:58:45 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* helm_release.ingress: rpc error: code = Unavailable desc = transport is closing
2018/10/30 15:58:45 [TRACE] [walkApply] Exiting eval tree: helm_release.ingress

2018/10/30 15:58:45 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error applying plan:

4 error(s) occurred:

* helm_release.prometheus: 1 error(s) occurred:

* helm_release.prometheus: rpc error: code = Unavailable desc = transport is closing
2018-10-30T15:58:45.341+0100 [DEBUG] plugin.terraform-provider-helm_v0.6.2_x4: 2018/10/30 15:58:45 [ERR] plugin: plugin server: accept unix /tmp/plugin858540935: use of closed network connection
* helm_release.grafana: 1 error(s) occurred:

* helm_release.grafana: rpc error: code = Unavailable desc = transport is closing
* helm_release.cert_manager: 1 error(s) occurred:

* helm_release.cert_manager: rpc error: code = Unavailable desc = transport is closing
* helm_release.ingress: 1 error(s) occurred:

* helm_release.ingress: rpc error: code = Unavailable desc = transport is closing

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


2018-10-30T15:58:45.384+0100 [DEBUG] plugin: plugin process exited: path=/home/denis/git/tranxfer-terraform/helm/.terraform/plugins/linux_amd64/terraform-provider-helm_v0.6.2_x4
```

**Comment by zzzuzik** [comment]
Alright guys, got the same error. Went through 3 hours of going down a rabbit hole through tracing TF/debugging docker/HELMing. Turned out, In my case, HELM was failing with port forwarding due to the lack of `sockat` package on the kubernetes host

the fix: `yum install -y socat`

I wish more details of helm handshake failures could be found in TF debug log

**Comment by zzzuzik** [comment]
btw, TF was reporting helm error, but the most irrelevant part:
`E1116 11:14:51.204985    1064 portforward.go:331] an error occurred forwarding 56079 -> 44134: error forwarding port 44134 to pod 4632f4f190709d665259de50a8543838e5777ecc551365457155cc9368ee5b7d, uid : unable to do port forwarding: socat not found.
Error: transport is closing
`

**Comment by denis111** [comment]
I have socat installed, my helm works fine outside terraform but not terraform's helm provider...

**Comment by mkozjak** [comment]
Installed `socat` helped and tiller was installed, but it was left hanging at `I0106 10:40:08.668595       1 reflector.go:240] Listing and watching *v1beta1.ValidatingWebhookConfiguration from github.com/appscode/voyager/vendor/github.com/appscode/kutil/tools/watch/informerwatcher.go:110` on installing a chart from Voyager (as an example). After a timeout was hit, I decided to test manually installing the chart by running:

```
helm del --purge voyager-operator --kubeconfig <path>
helm install appscode/voyager --name voyager-operator --version 8.0.1 --set cloudProvider=baremetal --kubeconfig <path>
```

The application started working:

```
KUBECONFIG=./kube_config_cluster.yml kubectl --namespace=default get deployments -l "release=voyager-operator, app=voyager"
NAME                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
voyager-voyager-operator   1         1         1            1           3m11s
```

Any ideas?

**Comment by mkozjak** [comment]
Decided to switch from this provider to https://github.com/sagikazarmark/terraform-tiller. Works better in combination with `local-exec` to install charts right after Tiller is ready.

**Comment by grugnog** [comment]
Having this issue around 20-30% of the time when initially installing a large chart (Gitlab).
I wonder if rather than relying on leaving the connection open to monitor the deploy it might be more reliable to initiate the install and then poll status?

**Comment by matthew-palmer** [comment]
This seems to be a fairly large issue with the current expected behavior of using a kubernetes config block, and how this provider actually works.

When using the method to setup the [kubernetes](https://github.com/terraform-providers/terraform-provider-kubernetes) provider, you can do the following to connect to a cluster (will be demonstrating with EKS):

```
# This is an example data setup for proper providers to be used for the cluster
provider aws {}
data "aws_iam_role" "admin_role" {
  name = var.cluster_admin_example
}

provider "aws" {
  alias = "eks"
  assume_role {
    role_arn    = data.aws_iam_role.admin_role
  }
}
data "aws_eks_cluster" "this" {
  name = var.cluster_name
}

data "aws_eks_cluster_auth" "this" {
  provider = aws.eks
  name     = var.cluster_name
}
```

```
# This WORKS
provider "kubernetes" {
  alias = "default"
  host                   = data.aws_eks_cluster.this.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.this.token
  load_config_file       = false
}
```

This above example works perfectly. The load_config_file is respected, and communication to/from the cluster works. `terraform apply` will result in a diff verification for resources as expected

However, this behavior does not translate to the helm provider.

```
# Does NOT work
provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.this.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.this.token
    load_config_file       = false
  }
}
```
On `terraform apply`, this will have the following behavior observed:

First, in a clean environment, an error will be reported that the ~/.kube/config file does not exist or attempt a dial of whatever cluster is in there. On an empty config, this attempts `localhost` each time.

The only thing that works for preventing read of the ~/.kube/config is by setting the environment variable `KUBE_LOAD_CONFIG_FILE`. This behavior is also problematic, in that it will prevent the loading if this environment variable is set to "true" or "false" or any value it seems. By setting it to an empty string or unsetting it seems to reset the kubeconfig behavior.

In any case, once the `KUBE_LOAD_CONFIG_FILE` is set, any combination of settings will always result in `Error rpc error: code = Unavailable desc = transport is closing`. I think the root issue is the kubernetes configuration block is not kept in sync with the kubernetes provider (which will cause this unexpected behavior).

**EDIT Feb 6th, 2020** 
On further digging into the provider, it seems that a large portion of the providers variables do not work as expected. When specifying the helm `service_account` to use, it still installs with default in the kube-system namespace, and `enable_tls` also has no effect when set. 
I am wondering if this is a bigger issue with the interactions between the version of terraform (0.12.x) and this provider. Unfortunately our implementation of terraform modules are using strictly 0.12.12+ terraform, so I would need to put together a test case just to see if this is why. Regardless, when provided with a valid kubeconfig, the provider installs helm charts as expected. Our work around for now is to initialize helm outside of this terraform provider, and then run this from a precompiled kubeconfig.

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
