### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by andrewrynhard** [hashicorp/terraform-provider-helm#22]
Building from `HEAD`:
```
make build
==> Checking that code complies with gofmt requirements...
go install
# github.com/mcuadros/terraform-provider-helm/vendor/github.com/hashicorp/terraform/config
vendor/github.com/hashicorp/terraform/config/testing.go:9: t.Helper undefined (type *testing.T has no field or method Helper)
make: *** [build] Error 2
```

**Comment by BenjaminDavison** [comment]
You need to use go 1.9

**Comment by andrewrynhard** [comment]
@BenjaminDavison :)
@mcuadros 
Now I'm getting
```
Error asking for user input: 1 error(s) occurred:

* provider.helm: dial unix /var/folders/sy/qh4qyxxj76340bgw0ntv_3y80000gn/T/plugin225172455|netrpc: connect: no such file or directory
```
when using the provider. Ran into this issue before. I have tried updating the dependencies with `glide up` and `glide install --strip-vendor`, but both break the build. How should we be updating the dependencies?

**Comment by mcuadros** [comment]
Why you need to update the dependencies? The mix of k8s and terraform ends is a dependency hell. 

To update the dependencies also use `--strip-vendor` and after apply [this](https://github.com/mcuadros/terraform-provider-helm/blob/master/scripts/fix-vendoring.sh) script, to fix the code. But this doesn't mean that will work. :(

The problem you showed is because a very modern `go-client` is being use and terraform is not using this version. This problem is happening in master? Because the last version is working for us, without any problem. Which version of terraform are you using?

**Comment by andrewrynhard** [comment]
Gah... wrong TF version. Sorry for the noise.
