### ISSUE TITLE
releases vs tags in github

### ISSUE THREAD

**Issue by thomasLeclaire** [hashicorp/terraform-provider-helm#268]
Hello,

why don't you use anymore the release feature of github? 
we have currently mix of release and tag, and the official last release (which is therefore considered like the default one of the project) is v 0.6.0 and not 0.9.1 like it should.

https://github.com/terraform-providers/terraform-provider-helm/releases

thx!

**Comment by rporres** [comment]
When this project was transferred to `terraform-providers` organization, we started following the standard practices there, which in terms of releases means that we use the `CHANGELOG.md` file to hold the release information instead of the github release page.

I do agree that the current state is not the ideal, though, as it can lead to confusion.

@alexsomesan What should we do here? We could move all the information of the previous releases to `CHANGELOG.md` but we would also need to upload them into https://releases.hashicorp.com/terraform-provider-helm/. I wouldn't like to just delete the old releases information as they contain a lot of history about the development of this provider

**Comment by rporres** [comment]
Let's follow up this in #331
