### ISSUE TITLE
helm releases not reinstalled after cluster recreation

### ISSUE THREAD

**Issue by blancqua** [hashicorp/terraform-provider-helm#297]
### Terraform Version
0.12.1

### Affected Resource(s)
- helm_resource
- azurerm_kubernetes_cluster

### Terraform Configuration Files
```hcl
resource "azurerm_kubernetes_cluster" "k8s" {
  ...
}
...
resource "helm_release" "application" {
  ...
  depends_on = [azurerm_kubernetes_cluster.k8s]
}
```

### Expected Behavior
Some tweaking on the configuration of the azurerm_kubernetes_cluster caused a recreation of the AKS cluster. This means that all helm charts which were deployed on the cluster should also be recreated.

### Actual Behavior
The AKS cluster gets recreated, the helm_release is not reinstalled. Terraform thinks it is still there (it is still in the state file).

**Comment by rehevkor5** [comment]
This seems to be a problem in AWS using EKS, too. The Helm provider doesn't appear to be able to detect that the cluster has been replaced.

**Comment by mstrzele** [comment]
My workaround for this is to set the value that isn't used in the chart and pass the ID of the cluster:
```
set {
  name  = "azurerm_kubernetes_cluster_id"
  value = "${azurerm_kubernetes_cluster.foo.id}"
}
```

No need to add `depends_on` in this case.

**Comment by hajdukd** [comment]
@mstrzele Does not work on AKS at least. It just marks helm_releases as "to be updated-in-place", instead of recreating them (not used property is just updated in tfstate from null/old value to new one).

There seems also to be an issue of missing tiller (for helm provider before helm 3.0) after AKS recreation. Terraform does not recognize there is no tiller installed and provider has to be initialized again.

Edit. After some time I've switched to a solution not using helm-provider at all and using helm directly from terraform. Works correctly at least to all the use-cases I have.

**Comment by mralanlee** [comment]
I was running into the same issue. My work around was running the following:

```bash
terraform taint helm_release.example
```

**Comment by vukasin-nikodijevic** [comment]
I just workaround this today by deleting all kubernetes and helm related entries from the state:

```
$ terraform state list | grep -E "^helm_release" | while read a; do terraform state rm "${a}"; done
$ terraform state list | grep -E "^kubernetes_" | while read a; do terraform state rm "${a}"; done
```
After this tf apply works.

This is logical flow of actions but I expect to have it automated. 
Really, after cluster has been recreated I expect to have all disconnected resources removed from the state.

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
