### ISSUE TITLE
helm provider is requesting permission out of chart namespace

### ISSUE THREAD

**Issue by neo-liang-sap** [hashicorp/terraform-provider-helm#470]
Say i have an kubeconfig which only have access to some namespace e.g. (garden-test-neo) in my code.

When i use helm provider to install an chart, although i specify namespace to garden-test-neo in my chart, helm is still requesting permission to default namespaces which causing fail.

```
Error: query: failed to query with labels: secrets is forbidden: User "system:serviceaccount:garden-neo-test:robot" cannot list resource "secrets" in API group "" in the namespace "default"

  on test.tf line 7, in resource "helm_release" "local":
   7: resource "helm_release" "local" {
```

### Terraform Version and Provider Version
Terraform v0.12.24
+ provider.helm v1.1.1

### Provider Version
provider.helm v1.1.1

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
provider "helm" {
  kubernetes {
    config_path = "~/Downloads/kubeconfig (3).yaml"
  }
}

resource "helm_release" "local" {
  name       = "gardener-chart-demo"
  chart      = "."
}
```

### Debug Output
```
Error: query: failed to query with labels: secrets is forbidden: User "system:serviceaccount:garden-neo-test:robot" cannot list resource "secrets" in API group "" in the namespace "default"

  on test.tf line 7, in resource "helm_release" "local":
   7: resource "helm_release" "local" {
```

### Expected Behavior
tf apply should be success

### Actual Behavior
tf apply failed

### Steps to Reproduce
my code is at https://github.com/neo-liang-sap/gardener-chart-demo

1. i can install the demo chart (install a configmap) using `helm install test .`
2. i can't install the demo chart via helm provider, when i run `tf apply`, the error is

```
Error: query: failed to query with labels: secrets is forbidden: User "system:serviceaccount:garden-neo-test:robot" cannot list resource "secrets" in API group "" in the namespace "default"

  on test.tf line 7, in resource "helm_release" "local":
   7: resource "helm_release" "local" {
```

**Comment by shibumi** [comment]
Hi @neo-liang-sap I ran into the same issue with helm but in combination with Tekton. I guess you are missing a serviceAccount, a Role and a RoleBinding for it. I don't think this bug is related to terraform at all.

**Comment by betabandido** [comment]
I ran into what it might be the same issue, and in my case it turned out I was trying to create the helm release as part of the same `terraform apply` where I was also creating the cluster. That means I was initializing the helm provider with values obtained from terraform resources (`aws_eks_cluster` and `aws_eks_cluster_auth`) instead of using data sources.

The [documentation for the kubernetes provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources) advises against doing this:

> WARNING
When using interpolation to pass credentials to the Kubernetes provider from other resources, these resources SHOULD NOT be created in the same apply operation where Kubernetes provider resources are also used. This will lead to intermittent and unpredictable errors which are hard to debug and diagnose. The root issue lies with the order in which Terraform itself evaluates the provider blocks vs. actual resources. Please refer to this section of Terraform docs for further explanation.

After I separately created the cluster and helm release creation in two different `terraform apply` executions, the issue went away.

This might not be the same issue @neo-liang-sap was experiencing, but hopefully it might help others arriving here.
