### ISSUE TITLE
Flow all outputs to helm

### ISSUE THREAD

**Issue by atrauzzi** [hashicorp/terraform-provider-helm#489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would love to have a way to flow all the outputs of my terraform-ing to helm to avoid having to pick them out one by one using `set` blocks. Would definitely cut down on a lot of boilerplate.

### Potential Terraform Configuration

```hcl
resource "helm_release" "my-huge-helm-umbrella" {
  name  = "my-umbrella"
  chart = "stable/umbrella"
  flow_outputs = true
}
```

**Comment by alexsomesan** [comment]
Unfortunately, this mechanism is not possible to implement on  the provider side alone. It would require changes to Terraform itself at the very least.
We do recognise that it would be a simpler user experience in some cases. If you are still interested in pursuing this idea I suggest opening an issue in the Terraform repository and explain the proposal there. I do have to speculate it would be unlikely to get a lot of traction since it's a very specific thing that requires a lot of changes to accommodate.
