### ISSUE TITLE
Tiller image is not installed 

### ISSUE THREAD

**Issue by mkubik** [hashicorp/terraform-provider-helm#50]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
- Terraform v0.11.3

### Affected Resource(s)
Please list the resources as a list, for example:
- helm provider

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "helm" {
  debug                     = "true"
  tiller_image              = "gcr.io/kubernetes-helm/tiller:v2.8.1"
  kubernetes {
      config_path           = "${var.config_file_path}"
  }
}
```

### Debug Output
- n/a
### Panic Output
- n/a
### Expected Behavior
tiller should have been deployed

### Actual Behavior
tiller was not deployed, resulting in 
```
Error: Error applying plan:

1 error(s) occurred:

* helm_chart.helmchart: 1 error(s) occurred:

* helm_chart.helmchart: error installing: Post http://localhost/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp [::1]:80: getsockopt: connection refused
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
- none

### References
- none

**Comment by mcuadros** [comment]
The problem is that can't connect to the k8s, looks like your credentials a wrong

**Comment by mkubik** [comment]
Interesting, you're right. I now used a different config, now I get

```
Error: Error applying plan:

1 error(s) occurred:

* helm_chart.helmchart: 1 error(s) occurred:

* helm_chart.helmchart: error creating tunnel: "could not find a ready tiller pod"
```
with the same tf config.

**Comment by mkubik** [comment]
found
```
container "tiller" in pod "tiller-deploy-675678b54-s54n6" is waiting to start: trying and failing to pull image
```
in the logs. investigating...

**Comment by mkubik** [comment]
works now, looks like it doesn't like 
`tiller_image              = "gcr.io/kubernetes-helm/tiller:latest"`
bur rather 
`tiller_image              = "gcr.io/kubernetes-helm/tiller:v2.8.1"`

Also, running `terraform plan` on a cluster without helm installed will fail as it is actively looking for tiller.

**Comment by johnmarcou** [comment]
Hi,
Thank you for Helm Terraform provider.
I am experimenting the same issue. I'd like to report what I have found during my test.

I am using Terraform to:
 - deploy a Kubernetes cluster (based on Typhoon),
 - and then, deploy helm packages on it

My understanding is the `helm provider` is "trying" to install Tiller when the provider is initialised.
But the thing is, Kubernetes API is "not yet available", since it's still "in deployment" at that stage.
NB: the `helm_release` resources are `depends_on = ["null_resource.kubernetes-is-online"]`, which is a little `kubectl cluster-info` return code checker.

It looks like:
 - t0: `terraform apply`
 - t1: Terraform `helm` provider is initialised, trying to deploy Tiller, but crashes
 - t2: Kubernetes deployment starts with Typhoon
 - t3: Kubernetes is deployed and available
 - t4: `null_resource.kubernetes-is-online` is Done
 - t5: helm provider starts to deploy `helm release` resources, but Tiller is not accessible


Workaround
------------
Adding a `helm init` command right after the `null_resource.kubernetes-is-online` checker fixed the issue. This would be:
 -  t3.5 : Deploy Tiller with `helm init`

Or, you can simply `terraform apply` twice.

Solution?
---------
`helm provider` could check if Tiller has been deployed (otherwise deploy it) when it wants to create a `helm_release` resource.

Thank you for your help.

**Comment by dminca** [comment]
The error is caused by the `Tiller` Pod that's not up and running yet.
A `sleep 5` must be configured to enable the Pod to finish booting before issuing any future Helm commands...
