### ISSUE TITLE
Add support for depends_on to provider

### ISSUE THREAD

**Issue by tmaier** [hashicorp/terraform-provider-helm#53]
I want to set up Tiller with a Service Account.
This requires that the Service Account is being created before Tiller gets installed.
I have a module to install the Service Account and the ClusterRoleBinding.

I need to enforce that the module runs before the provider is being executed.

helm provider should support the depends_on command in order that Terraform can set up a proper dependency graph

How to emulate `depends_on` for modules: https://medium.com/@bonya/terraform-adding-depends-on-to-your-custom-modules-453754a8043e

**Comment by Jeeppler** [comment]
I need the ability to use `depens_on` to create a IAM policy before installing a helm release.

**Comment by chrisferry** [comment]
I also need depends_on functionality as we require some scripting to run before the provider can install tiller.  Any idea when/if this will supported?

**Comment by rporres** [comment]
The main issue here is tiller being part of the provider, so no easy way to fix this. Having a tiller as a separate resource it could definitely fix things, as suggested in #134. There's some work on it, but has its own issues and since helm is moving away from tiller it may not be merged.

If you absolutely need this a workaround can be to avoid installing the tiller with the provider and create a k8s deployment for it that you manage with the terraform k8s provider

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
