### ISSUE TITLE
helm_release using s3 repository

### ISSUE THREAD

**Issue by bluemalkin** [hashicorp/terraform-provider-helm#609]
Hi,

With the depreciation of the helm_repository data source, the docs to not make it clear enough on how I can provide a repository URL in the form of s3://BUCKET_NAME.

I have no issues adding the repo and installing the chart using helm cli (with aws credentials setup), in terraform I get thrown the error:
```
resource "helm_release" "example" {
  name       = "example"
  repository = "s3://BUCKET/charts"
  chart      = "example"
  namespace  = kubernetes_namespace.test.metadata[0].name
}
```

Results in
```
Error: looks like "s3://BUCKET/charts" is not a valid chart repository or cannot be reached: plugin "bin/helms3" exited with error
```

Unfortunately I am not able to get more details using DEBUG logging.

What is the exact expect syntax for repository attribute and how does it deal with the AWS authentication to s3:// ?

Thanks !

**Comment by jrhouston** [comment]
Thanks for opening this @bluemalkin. I was able to get this to work just by using the `s3://bucket-name` format as the value for the `repository` field. 

Is there a `index.yaml` when you run `aws s3 ls s3://BUCKET/charts`? That particular error happens when [helm fails to download the index.yaml](https://github.com/helm/helm/blob/4e0bd3483b4edec6f21a10484953024501c20b92/pkg/repo/chartrepo.go#L236:L239) for the repository. So that points to either the wrong path to the repo, or an issue with the AWS credentials. The provider defers to the helm package, which in turn defers to the helm-s3 plugin for how to source those credentials. There is a [note](https://github.com/hypnoglow/helm-s3#note-on-aws-authentication) about this on the helm-s3 github repository, which says it sources them using the same method as the AWS CLI. I was able to get it to work just by setting the basic `AWS_` environment variables.

It is annoying that the error message from the plugin seems to be getting swallowed. Using the helm cli I am able to get it to spit out a more specific error if i have bad credentials or the wrong path. However, it looks as though the error from the plugin just [gets written to stderr](https://github.com/helm/helm/blob/master/pkg/getter/plugingetter.go#L80) instead of captured as an error and a [generic one](https://github.com/helm/helm/blob/master/pkg/getter/plugingetter.go#L81) is passed along instead – so it gets swallowed before the error bubbles up to the provider. We would have to propose an upstream change to helm in order to capture it inside an `error` that could be shown by the provider.

**Comment by bluemalkin** [comment]
Hi @jrhouston  thanks for the message.

I have solved my issues.

One was your /charts suffix, I removed it.

Then I worked out that I needed to add an environment variable `AWS_PROFILE=<name>` to make helm point to the right AWS credentials.

I agree that the plugin could be a bit more verbose with errors!

Cheers,
