### ISSUE TITLE
Way to have set_sensitive helm values not appear in state?

### ISSUE THREAD

**Issue by red8888** [hashicorp/terraform-provider-helm#619]
I can exclude a helm value from plan/diff output like this: 
```
  set_sensitive {
    name  = "mySecretValue"
    value = "I dont want this in state!"
  }
```

My state is encrypted and secure etc but I still dont want this to even appear in my tf state

Is there a way to do something almost like always ignore lifecycle on a helm value? I want terraform to set the value the first time and ignore it after that (like ignore lifecycle does) but I also dont want terraform to keep it in state either

Is there a way to do that with this provider?

There are a bunch of helm charts that will create k8s secrets for you which are super easy to use. I want to pass the secret strings in set_sensitive{} from env vars with terraform. I can do that now but terraform will keep the value in state- so that last bit is a sticking point for me.

**Comment by dak1n1** [comment]
This is a really good question. I didn't know the answer so I did some research and testing to see if I could find a work-around to this issue.

[This post](https://discuss.hashicorp.com/t/passwords-sensitive-data-in-tfstate-files/2446/2) contains the best description I found explaining the issue:

```
Whether a value is stored in the state depends on how it is used
rather than how it is passed in to Terraform. Any value you use in
the arguments inside a resource or data block, along with any
values exported by the resource type or data source, will always
be in the state, so that they can be used for planning on future runs.

There are some specific places you can use values where
they will not appear in the state:

* Inside provider blocks
* Inside provisioner blocks within resource blocks
* Inside connection blocks within resource or provisioner blocks
```

Since `set_sensitive` is part of a resource block, it will always end up in state. I tested creating a resource using `set_sensitive` to see if there was any way I could remove this data once the resource is created. It looks like the lifecycle block does indeed work on this. Though the value will be placed into state initially, you can edit the state to remove it, and the lifecycle block seems to be able to keep it from getting overwritten.

Here's the config I used to test this:

```hcl
variable "SECRET_STRING" {}

resource "helm_release" "mydatabase" {
  name  = "mydatabase"
  chart = "mariadb"
  repository = "https://charts.bitnami.com/bitnami"

  set {
    name  = "mariadbUser"
    value = "foo"
  }

  set_sensitive {
    name  = "mariadbPassword"
    value = var.SECRET_STRING
    type  = "string"
  }

  lifecycle {
    ignore_changes = [metadata.0.values, set_sensitive]
  }
}
```

Then I can pass the secret value in via the command line (or environment variable) to avoid placing it into the Terraform config:
```shell
$ terraform init
$ KUBE_CONFIG_PATH="${HOME}/.kube/config" TF_VAR_SECRET_STRING=asdfhjkl terraform apply --auto-approve=true
```

The state initially contains this value, but I can remove it and add a placeholder ("") instead:
```shell
$ grep asdf terraform.tfstate
                "value": "asdfhjkl"
```

Editing the state, I replace this sensitive value with a blank string:

```hcl
            "set_sensitive": [
              {
                "name": "mariadbPassword",
                "type": "string",
                "value": ""
              }
            ],
```

Then apply again, and even though I'm giving it the sensitive value, it does not insert that value into state.

```shell
$ KUBE_CONFIG_PATH="${HOME}/.kube/config" TF_VAR_SECRET_STRING=asdfhjkl terraform apply --auto-approve=true
$ grep asdf terraform.tfstate
$
```

This is a pretty clumsy work-around that will be difficult to implement with a remote state. But the only other work-around I was able to find was to `terraform state rm` the entire resource. Also, I think it required this change I made to my local testing branch of the provider:

```diff
+++ b/helm/resource_release.go
@@ -163,7 +163,7 @@ func resourceRelease() *schema.Resource {
                                                },
                                                "value": {
                                                        Type:      schema.TypeString,
-                                                       Required:  true,
+                                                       Optional:  true,
                                                        Sensitive: true,
                                                },
                                                "type
```

I'll have to discuss this with my team, to see if this change is something they would be comfortable with. Another option would be to move the `set_sensitive` attribute to the provider level and see if we can keep it out of state that way.

**Comment by red8888** [comment]
This arguably more a tf "issue" or challenge then something specific to this provider so I really appreciate you looking into this!

It would be amazing if the helm provider could do this though. It seems like it's common now for charts to create k8s secrets for you which is really convenient. If I could reference those secret values via ENV vars and have helm not store them in state that would be soooo awesome!

**Comment by idan-gur** [comment]
Does anyone have an update on this?
We want to be able to use `set_sensitive` and have it's values never get to the remote-state.
