### ISSUE TITLE
same chart name in different clusters failed

### ISSUE THREAD

**Issue by katlimruiz** [hashicorp/terraform-provider-helm#631]
### Terraform Version and Provider Version
Terraform v0.13.5

### Provider Version
    helm = {
      source  = "hashicorp/helm"
      version = "~> 1.3"
    }

    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 1.13"
    }

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
I have this structure
```
--index.tf
--/production
----main.tf
--/staging
----main.tf
--/common
----/certmanager
------main.tf
```

**index.tf**
```hcl
module "production" {
  source = "./production"
}
module "staging" {
  source = "./staging"
}
```

**production/main.tf**
```hcl
module "certmanager" {
  source             = "../m/certmanager"
  kubweb_config_file = "${local.kubweb}/config.txt"
  env = local.env
}
```

**common/certmanager/main.tf**
```hcl
provider "kubernetes" {
  config_path = var.kubweb_config_file
}
provider "helm" {
  kubernetes {
    config_path = var.kubweb_config_file
  }
}
resource "helm_release" "certmanager" {
  name             = "cert-manager"
  repository       = "https://charts.jetstack.io"
  chart            = "cert-manager"
  version          = "1.1.0"
  namespace        = "cert-manager"
  create_namespace = true
  timeout = 120
}
```

### Debug Output
```
Error: cannot re-use a name that is still in use

  on m\certmanager\main.tf line 13, in resource "helm_release" "certmanager":
  13: resource "helm_release" "certmanager" {
```

### Expected Behavior
It should allow to have the release name since it is within a separate module (and they target different kub clusters)

### Actual Behavior
It cannot support the same release name.

As a workaround I had to add the env to the release name
```
resource "helm_release" "certmanager" {
  name             = "cert-manager-${local.env}"
  repository       = "https://charts.jetstack.io"
```

And that is funny because I have the same setup with ambassador gateway and it does use the same releease name for each module

### Steps to Reproduce
1. `terraform plan`
1. `terraform apply`

Plan does work ok. Apply fails.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by redeux** [comment]
Hi @katlimruiz, thanks for opening this issue.  I tried to recreate your problem with the information you provided, I wasn't able to get the same outcome.  Certmanager was provisioned correctly into the separate production and staging clusters.  

Is it possible that you're accidently loading the same kubeconfig for the production and staging clusters?  That would explain why you're seeing a collision on the release name.

If you think that's not the case, can you [provide a log](https://www.terraform.io/docs/internals/debugging.html) of the failed apply in a gist?

As an aside, there is another pattern I've seen folks use for similar use cases, where the providers are given to the module, rather than defined in the module.  I don't know enough about your environment to recommend this approach, but it can make things easier to troubleshoot, in my experience.

```HCL
provider "helm" {
  alias = "production"
  kubernetes {
    config_context = "minikube"
  }
}

provider "helm" {
  alias = "staging"
  kubernetes {
    config_context = "kind-kind"
  }
}

module "production" {
  providers = {
    helm = helm.production
  }
  source = "./production"
}

module "staging" {
  providers = {
    helm = helm.staging
  }
  source = "./staging"
}
```
