### ISSUE TITLE
how do i run "helm init" with this provider?

### ISSUE THREAD

**Issue by babatundebusari** [hashicorp/terraform-provider-helm#78]
Anyway to run something similar to `helm init` using this provider with terraform or no way to to this?

thanks

**Comment by mcanevet** [comment]
I think it should be possible to run the equivalent of `helm init -c` using the Helm library at every run because, unless I'm wrong, this process is idempotent.

**Comment by mkyc** [comment]
there is workaround

```
resource "null_resource" "helm_init" {
  provisioner "local-exec" {
    command = "echo \"$(terraform output kube_config)\" > ./azurek8s"
  }
  provisioner "local-exec" {
    command = "export KUBECONFIG=./azurek8s"
  }
  provisioner "local-exec" {
    command = "helm init"
    environment {
      KUBECONFIG = "./azurek8s"
    }
  }
}
```

**Comment by dominik-lekse** [comment]
@mkyc Thanks for sharing the workaround snippet.

**Comment by Chrisjw42** [comment]
Is this still the recommended method to run helm init?

**Comment by CodeSwimBikeRun** [comment]
I'm still lost how to do this @mkyc  was downvoted for a reason, its not clear what all that kube_config copying is doing.

**Comment by rporres** [comment]
`helm init` does a client and a server initialisation. Server initialisation means installing the tiller, which is covered. Client initialisation is not yet there, but it will be fixed with #185

**Comment by pdecat** [comment]
Support for helm initialization was released with [v0.10.0 of the helm provider](https://github.com/terraform-providers/terraform-provider-helm/blob/master/CHANGELOG.md#0100-june-18-2019).

**Comment by rporres** [comment]
Closing this as both client and server initialisation are covered

**Comment by galindro** [comment]
@rporres when helm provider will execute the "helm init"? I'm asking this because I would like to just execute it without install any helm file. I was though that only the provider declaration was sufficient, but it seems not working. So, I've just added a dummy `helm_repository` data source to force the refresh. Doesn't works as well...

**Comment by rporres** [comment]
Initialization is done silent and turned on by default

* Client is initialized in https://github.com/terraform-providers/terraform-provider-helm/blob/master/helm/provider.go#L260. You can turn off this behaviour using the `init_helm_home` option. 
* Server is initialized in https://github.com/terraform-providers/terraform-provider-helm/blob/master/helm/provider.go#L429. You can turn off this behaviour using the `install_tiller ` option

Since `helm_repository` deals with local directories, you will get client initialized if you use that but you will need a release to force the provider to install tiller to communicate with server

**Comment by eskp** [comment]
@rporres could you tell us at what stage the initialization is done? I have an external data resource to query helm however helm doesn't seem to be initialized (`.helm` does not exist) when the script runs.
