### ISSUE TITLE
"replace" argument doesn't seem work (unless I just don't understand what it's meant to do)

### ISSUE THREAD

**Issue by vdavidoff** [hashicorp/terraform-provider-helm#784]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: v0.13.5
Provider version: 2.3.0
Kubernetes version: 1.16
```

### Affected Resource(s)

- helm_release

### Expected Behavior

Setting `replace` to `true` should cause the Helm provider to "adopt" releases that already exist, that have been deployed by helm outside of terraform enterprise.

### Actual Behavior

Setting `replace` to `true` continues to result in errors like `cannot re-use a name that is still in use`

To get terraform enterprise to adopt releases as described I am having to delete the release Secrets the previous Helm deploy created, at which point in time the helm provider seems to do the right thing, adopting the existing release into its local state in terraform enterprise.

It is entirely possible I don't understand what `replace` is supposed to do but the help docs seem to suggest I am not misunderstanding.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Thanks for opening this @vdavidoff – the `replace` attribute (the same as the `--replace` option on the helm CLI) only replaces an existing release if it is in the failed or uninstalled state. See the logic of the install action here: https://github.com/hashicorp/terraform-provider-helm/blob/9314962e66485e7b7d0dbffa1685bb182c96ab50/vendor/helm.sh/helm/v3/pkg/action/install.go#L439

So this is actually expected behaviour if the helm release was previously installed successfully. It looks like our provider docs are actually incorrect, and should be in line with what it says in the helm documentation:

> --replace    re-use the given name, only if that name is a deleted release which remains in the history. This is unsafe in production

**Comment by vdavidoff** [comment]
Ah, I see. OK, thank you for the explanation.

**Comment by jrhouston** [comment]
Fixed the documentation [here](https://github.com/hashicorp/terraform-provider-helm/commit/82fe05d4f85b12a200fb9dfc6a70737f36c39049).
