### ISSUE TITLE
KEDA `destroy` gets stuck

### ISSUE THREAD

**Issue by DaleyKD** [hashicorp/terraform-provider-helm#939]
If you prefer, you can also ask your question in the Kubernetes community Slack channel [#terraform-providers](https://kubernetes.slack.com/messages/CJY6ATQH4). ([Sign up here](http://slack.k8s.io/))

## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.2.6
Helm Provider version: 2.6.0
Kubernetes version: AKS 1.23.8
```
## Terraform configuration
```hcl
# Create the K8S namespace for KEDA
resource "kubernetes_namespace" "keda" {
  metadata {
    name = "keda"
  }
}

# Install KEDA into K8S
# https://github.com/kedacore/keda
resource "helm_release" "keda" {
  name       = "keda"
  repository = "https://kedacore.github.io/charts"
  chart      = "keda"
  version    = "2.8.1"
  namespace  = kubernetes_namespace.keda.metadata.0.name

  set {
    name  = "podIdentity.activeDirectory.identity"
    value = "${var.aad_pod_identity_name}-binding"
  }

  set {
    name  = "http.timeout"
    value = "90000"
  }
}
```

## Question
Currently, when `terraform destroy` on this resource, it gets stuck and never finishes, even if the timeout increases. I suspect it has something to do with its finalizer.

According to https://keda.sh/docs/2.8/deploy/#uninstall , we need to execute `kubectl delete $(kubectl get scaledobjects,scaledjobs -oname)` first.

I find it hard to believe that I'm the first person to have a problem with destroying KEDA via the Helm provider. I know I'm not the first to use this provider to install KEDA.

Am I doing something wrong? Is there any way to be sure to remove the ScaledObjects, etc. first?

**Comment by arybolovlev** [comment]
Hi @DaleyKD,

Below are a bit more details on why it fails, but in general, you need to take care of installed CRs and that really depends on how you installed them.
 
As you can see KEDA Helm chart installs some CRDs:
```
# kubectl get crds
NAME                                    CREATED AT
clustertriggerauthentications.keda.sh   2022-08-24T15:03:23Z
scaledjobs.keda.sh                      2022-08-24T15:03:23Z
scaledobjects.keda.sh                   2022-08-24T15:03:23Z
triggerauthentications.keda.sh          2022-08-24T15:03:23Z
```

Normally, a CRD(Custom Resource Definition) cannot be removed if there is at least one related CR(Custom Resource). When you execute `terraform destroy` against your code, the Helm provider is trying to delete all CRDs and waiting for this operation to succeed. That is because by default `wait` attribute is `true`. More details about this attribute are in our documentation [here](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#wait). It fails once the time is out because one or more CRDs were not removed, since there is at least one related CR. This is expected behavior and that is why KEDA documentation says that you have to delete all related CRs before you delete CRDs.

You can set `wait` to `false` and the Helm provider won't wait while CRDs get uninstalled and report success in a few seconds. This will emulate Helm's behavior. As you can see in their [source code](https://github.com/helm/helm/blob/main/cmd/helm/uninstall.go#L74) `wait` is `false` by default. That is the reason why using Helm to uninstall and the Helm provider has different results. In this case, you still have to do manual clean-up since some resources remain orphans.

I hope that helps.

**Comment by DaleyKD** [comment]
What an AWESOME writeup, and full of links/help. Thank you so much for taking the time to educate me.

I figured it had something to do with removing the CRDs, but didn't think about having associated CRs (I'm REALLY new to K8S).

Final question: Is there a way to tell our `helm_release` resource to use `wait = true` on apply, but `wait = false` on destroy?

**Comment by arybolovlev** [comment]
Good question, but, unfortunately, I have to say that there is no way to detect `apply\plan` or `destroy` within the TF code. You may consider using a variable to keep the value for this attribute. In this case, you can change it on the fly when applying or destroying resources. Still not the perfect solution, but better than nothing. 😊

```hcl
variable "helm_release_wait" {
    default = true
}

resource "helm_release" "this" {
  ...
  wait = var.helm_release_wait
}
```

Apply:
```
# terraform apply
```

Destroy:
```
# terraform destroy -var="helm_release_wait=false"
```

**Comment by DaleyKD** [comment]
That was what I figured I'd have to do. I'm surprised that Terraform doesn't have some built in variable/function to let us know what the operation is.

Thanks again!
